---
title: "Text Cloud"
output: html_document
---
##網路爬蟲-Ptt婚姻版

```{r}
source('pttTestFunction.R')
id = c(1988:1995)
URL = paste0("https://www.ptt.cc/bbs/marriage/index", id, ".html")
filename = paste0(id, ".txt")
pttTestFunction(URL[1], filename[1])
mapply(pttTestFunction, 
       URL = URL, filename = filename)

```

## 篩選字詞

```{r}
library(tmcn)
library(NLP)
library(tm)
library(jiebaRD)
library(jiebaR)
library(RColorBrewer)
library(wordcloud)
library(rvest)
rm(list=ls(all.names = TRUE))
filenames <- list.files(getwd(), pattern="*.txt")
files <- lapply(filenames, readLines)
docs <- Corpus(VectorSource(files))
toSpace <- content_transformer(function(x, pattern) {
  return (gsub(pattern, " ", x))
}
)
warning=FALSE
suppressWarnings(warning())
cc=worker()
new_user_word(cc,"公公","n")
new_user_word(cc,"婆婆","n")
new_user_word(cc,"花錢","n")
new_user_word(cc,"花太多","n")
new_user_word(cc,"出走","n")
new_user_word(cc,"離家出走","n")
new_user_word(cc,"看看","a")
docs <- tm_map(docs, toSpace, "可否")
docs <- tm_map(docs, toSpace, "可")
docs <- tm_map(docs, toSpace, "然")
docs <- tm_map(docs, toSpace, "讓")
docs <- tm_map(docs, toSpace, "因為")
docs <- tm_map(docs, toSpace, "應該")
docs <- tm_map(docs, toSpace, "樣")
docs <- tm_map(docs, toSpace, "※")
docs <- tm_map(docs, toSpace, "◆")
docs <- tm_map(docs, toSpace, "‧")
docs <- tm_map(docs, toSpace, "或")
docs <- tm_map(docs, toSpace, "再")
docs <- tm_map(docs, toSpace, "現")
docs <- tm_map(docs, toSpace, "話")
docs <- tm_map(docs, toSpace, "找")
docs <- tm_map(docs, toSpace, "文章")
docs <- tm_map(docs, toSpace, "對")
docs <- tm_map(docs, toSpace, "算")
docs <- tm_map(docs, toSpace, "原")
docs <- tm_map(docs, toSpace, "後")
docs <- tm_map(docs, toSpace, "個")
docs <- tm_map(docs, toSpace, "又")
docs <- tm_map(docs, toSpace, "那")
docs <- tm_map(docs, toSpace, "一")
docs <- tm_map(docs, toSpace, "用")
docs <- tm_map(docs, toSpace, "才")
docs <- tm_map(docs, toSpace, "過")
docs <- tm_map(docs, toSpace, "拿")
docs <- tm_map(docs, toSpace, "能")
docs <- tm_map(docs, toSpace, "被")
docs <- tm_map(docs, toSpace, "一個")
docs <- tm_map(docs, toSpace, "看")
docs <- tm_map(docs, toSpace, "推")
docs <- tm_map(docs, toSpace, "妳")
docs <- tm_map(docs, toSpace, "人")
docs <- tm_map(docs, toSpace, "什麼")
docs <- tm_map(docs, toSpace, "你")
docs <- tm_map(docs, toSpace, "的")
docs <- tm_map(docs, toSpace, "我")
docs <- tm_map(docs, toSpace, "是")
docs <- tm_map(docs, toSpace, "看板")
docs <- tm_map(docs, toSpace, "作者")
docs <- tm_map(docs, toSpace, "發信站")
docs <- tm_map(docs, toSpace, "批踢踢實業坊")
docs <- tm_map(docs, toSpace, "[a-zA-Z]")
docs <- tm_map(docs, toSpace, "吃")
docs <- tm_map(docs, toSpace, "有")
docs <- tm_map(docs, toSpace, "就")
docs <- tm_map(docs, toSpace, "了")
docs <- tm_map(docs, toSpace, "他")
docs <- tm_map(docs, toSpace, "嗎")
docs <- tm_map(docs, toSpace, "吧")
docs <- tm_map(docs, toSpace, "到")
docs <- tm_map(docs, toSpace, "要")
docs <- tm_map(docs, toSpace, "啊")
docs <- tm_map(docs, toSpace, "給")
docs <- tm_map(docs, toSpace, "在")
docs <- tm_map(docs, toSpace, "多")
docs <- tm_map(docs, toSpace, "真")
docs <- tm_map(docs, toSpace, "想")
docs <- tm_map(docs, toSpace, "只")
docs <- tm_map(docs, toSpace, "去")
docs <- tm_map(docs, toSpace, "噓")
docs <- tm_map(docs, toSpace, "萬")
docs <- tm_map(docs, toSpace, "也")
docs <- tm_map(docs, toSpace, "很")
docs <- tm_map(docs, toSpace, "食記")
docs <- tm_map(docs, toSpace, "所以")
docs <- tm_map(docs, toSpace, "店名")
docs <- tm_map(docs, toSpace, "電話")
docs <- tm_map(docs, toSpace, "地址")
docs <- tm_map(docs, toSpace, "價格")
docs <- tm_map(docs, toSpace, "營業時間")
docs <- tm_map(docs, toSpace, "用餐時間")
docs <- tm_map(docs, toSpace, "拍攝時間")
docs <- tm_map(docs, toSpace, "個人評價")
docs <- tm_map(docs, toSpace, "業配")
docs <- tm_map(docs, toSpace, "可以")
docs <- tm_map(docs, toSpace, "不")
docs <- tm_map(docs, toSpace, "都")
docs <- tm_map(docs, toSpace, "好")
docs <- tm_map(docs, toSpace, "跟")
docs <- tm_map(docs, toSpace, "會")
docs <- tm_map(docs, toSpace, "很惠")
docs <- tm_map(docs, toSpace, "來")
docs <- tm_map(docs, toSpace, "們")
docs <- tm_map(docs, toSpace, "這")
docs <- tm_map(docs, toSpace, "餐廳")
docs <- tm_map(docs, toSpace, "還有")
docs <- tm_map(docs, toSpace, "起來")
docs <- tm_map(docs, toSpace, "感覺")
docs <- tm_map(docs, toSpace, "覺得")
docs <- tm_map(docs, toSpace, "電話")
docs <- tm_map(docs, toSpace, "店家")
docs <- tm_map(docs, toSpace, "店家電話")
docs <- tm_map(docs, toSpace, "比較")
docs <- tm_map(docs, toSpace, "地址")
docs <- tm_map(docs, toSpace, "味道")
docs <- tm_map(docs, toSpace, "沒有")
docs <- tm_map(docs, toSpace, "消費")
docs <- tm_map(docs, toSpace, "還")
docs <- tm_map(docs, toSpace, "但")
docs <- tm_map(docs, toSpace, "時間")
docs <- tm_map(docs, toSpace, "和")
docs <- tm_map(docs, toSpace, "沒")
docs <- tm_map(docs, toSpace, "說")
docs <- tm_map(docs, toSpace, "兩")
docs <- tm_map(docs, toSpace, "月")
docs <- tm_map(docs, toSpace, "把")
docs <- tm_map(docs, toSpace, "問題")
docs <- tm_map(docs, toSpace, "怎麼")

docs <- tm_map(docs, removePunctuation)
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, stripWhitespace)
docs

```

## 詞頻矩陣


```{r }
mixseg = worker()
jieba_tokenizer=function(d){
  unlist(segment(d[[1]],mixseg))
}
seg = lapply(docs, jieba_tokenizer)
freqFrame = as.data.frame(table(unlist(seg)))
freqFrame = freqFrame[order(freqFrame$Freq,decreasing=TRUE), ]
library(knitr)
kable(head(freqFrame), format = "markdown")
```


##文字雲
此部分將頻率下限提高，顯示文字數量減少，order改為照頻率排序

```{r}
wordcloud(freqFrame$Var1,freqFrame$Freq,
          scale=c(5,0.1),min.freq=100,max.words=100,
          random.order=FALSE, random.color=FALSE, 
          rot.per=.1, colors=brewer.pal(8, "Dark2"),
          ordered.colors=FALSE,use.r.layout=FALSE,
          fixed.asp=TRUE)
```