---
title: "W3 intial"
output: html_document
---
##載入必要的package

```{r setup}
 library(bitops)
 library(httr)
 library(RCurl)
 library(XML)
 library(tm)
 library(NLP)
 library(tmcn)
 library(jiebaRD)
 library(jiebaR)
```
## 網路爬蟲

利用網路爬蟲存取所有文章的內文，並按照章節名稱儲存

```{ }
prefix = "http://www.sacred-texts.com/neu/mart/mart"
data <- list()
for (id in 0:502){
  a = sprintf("%.3d",id)
  url  <- paste0( prefix, a, ".htm" )
  html=htmlParse(url)     #(GET(url),encoding="UTF-8")，XML網站不須此處理
  major <- xpathSApply( html, "/html/body/pre/text()",xmlValue )
  #文章內文
  chapter <- xpathSApply( html, "/html/body/center[1]/h2", xmlValue )
  #章節名稱
  name <- paste0("C:/Users/user/Desktop/GITHUB/example/Week3/DAT/", chapter, ".txt")
  write(major, name, append = TRUE)
  }

```

## TF-IDF
```{}
d.corpus <- Corpus( DirSource("./DAT") )
mixseg = worker()
jieba_tokenizer = function(d)
{
  unlist( segment(d[[1]], mixseg) )
}
seg = lapply(d.corpus, jieba_tokenizer)

count_token = function(d)
{
  as.data.frame(table(d))
}
tokens = lapply(seg, count_token)

n = length(seg)
TDM = tokens[[1]]
colNames <- names(seg)
colNames <- gsub(".txt", "", colNames)
for( id in c(2:n) )
{
  TDM = merge(TDM, tokens[[id]], by="d", all = TRUE)
  names(TDM) = c('d', colNames[1:id])
}
TDM[is.na(TDM)] <- 0
library(knitr)
kable(head(TDM))
kable(tail(TDM))
```

#Failed Try
嘗試分析TF-IDF語法然後自己寫一個，失敗
```{}
  names=DirSource("./DAT")
  temp=readtext::readtext("./DAT")
  #成功讀取檔案並按照檔案名稱與內容儲存為data.frame
  temp1=strsplit(temp$text,split = " ")
  #失敗，無法分割\n換行
```
#Another Failed Try
 從檔案名稱中取出BOOK序號並將檔案依BOOK序號歸類，失敗
```{}
names = list.files("./DAT")
q=strsplit(names, split = " ")

for (book_num in 1:502) {
  r=q[[book_num]][5]
}
for迴圈輸出值是最後處理的數字，無法按照序號輸出

```


```{r}
d.corpus <- Corpus( DirSource("./DAT") )
mixseg = worker()
jieba_tokenizer = function(d){unlist( segment(d[[1]], mixseg) )}
seg = lapply(d.corpus, jieba_tokenizer)#unlist

count_token = function(d){ as.data.frame(table(d))}
tokens = lapply(seg, count_token)#轉成dataframe

n = length(seg)#字串長度
TDM = tokens[[1]]
colNames <- names(seg)
colNames <- gsub(".txt", "", colNames)#建立欄名稱
for( id in c(2:n) )
{
  TDM = merge(TDM, tokens[[id]], by="d", all = TRUE)
  names(TDM) = c('d', colNames[1:id])
}
TDM[is.na(TDM)] <- 0
kable(head(TDM))
kable(tail(TDM))
```